"""Qt 页面可调用的应用门面。"""

from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import Any, Protocol
from uuid import UUID

from kindergarten_manager.application.agent_runtime import ActiveScope, ToolResult
from kindergarten_manager.application.ai_generation import CoordinatorState, PreviewView
from kindergarten_manager.application.ai_settings import AiSettingsView
from kindergarten_manager.application.dto import CommandResult, OperationAccepted
from kindergarten_manager.application.lesson_plans import LessonPlanEditorState
from kindergarten_manager.application.workspace import DailyPlanContext, DesktopSettingsContext


class DesktopServices(Protocol):
    def complete_setup(self, values: dict[str, str]) -> None: ...

    def load_plan_context(self) -> DailyPlanContext: ...

    def select_plan_context(self, class_id: int, plan_date: date) -> DailyPlanContext: ...

    def load_current_plan(self) -> dict[str, Any]: ...

    def save_current_plan(self, content: dict[str, Any]) -> None: ...

    def load_settings(self) -> DesktopSettingsContext: ...

    def update_settings(self, values: dict[str, str]) -> DesktopSettingsContext: ...

    def suggested_export_filename(self) -> str: ...

    def export_current_day(self, destination: Path) -> None: ...

    def load_ai_settings(self) -> AiSettingsView: ...

    def save_ai_settings(self, values: dict[str, object]) -> AiSettingsView: ...

    def reset_ai_prompt(self, prompt_code: str) -> str: ...

    def load_ai_generation_state(self) -> CoordinatorState: ...

    def start_ai_generation(
        self,
        section_code: str,
        teacher_context: str,
    ) -> OperationAccepted: ...

    def start_ai_batch(self, teacher_context: str) -> OperationAccepted: ...

    def adopt_ai_preview(self, preview_id: int) -> LessonPlanEditorState: ...

    def reject_ai_preview(self, preview_id: int) -> PreviewView: ...

    def cancel_ai_generation(self, operation_id: UUID) -> CommandResult[None]: ...

    def load_agent_state(self) -> Any: ...

    def load_agent_context_request(self) -> ActiveScope: ...

    def start_agent_turn(self, intent: str, context_request: object) -> OperationAccepted: ...

    def cancel_agent_turn(self, operation_id: UUID) -> ToolResult[None]: ...

    def reject_agent_patch(self, patch_id: UUID) -> ToolResult[None]: ...
